const courses = [
  {
    "COURSE CODE": "AAS24-014",
    "CPE Title": "A History of the Suicide Hotline (from a Site Examiner Perspective)",
    "Part of Conference": "American Association of Suicidology 57th Annual Conference",
    "Sponsor": "American Association of Suicidology  ",
    "Virtual or Live": "In person",
    "Sponsor Type": "Professional Org",
    "CPE Date": "2024-05-07T00:00:00",
    "Description of Activity": "The modern day \"suicide hotline\" has its roots in both the field of suicidology and the grass-roots movement to de-stigmatize and help persons in a suicidal crisis. Since 1960, when several major hotlines began, hotlines have evolved from poorly funded \"do-gooder\" agencies using lay volunteers, to sophisticated technological service centers, perhaps still using volunteers, but with more guidance and standards from clinical and research communities. Once-held tenets in anonymity and the right of caller self-agency has morphed into the active intervention approach we have at most hotlines. The process of providing crisis intervention counseling has also changed, with more programs opting for less personal, technologically-backed approaches, and efforts to refer callers rather than \"talk them through\" the crisis. As a long-time A.A.S. Accreditation Site Examiner, I will share both a brief history of the suicide hotline, along with my personal observations of having worked in the field since 1980.",
    "Link": "Full Schedule",
    "Hours": "C",
    "DoDI Criteria Topics": "Prevention of Harmful Behaviors"
  },
  {
    "COURSE CODE": "AAS24-015",
    "CPE Title": "A Public Health Approach to Zero Suicide",
    "Part of Conference": "American Association of Suicidology 57th Annual Conference",
    "Sponsor": "American Association of Suicidology  ",
    "Virtual or Live": "In person",
    "Sponsor Type": "Professional Org",
    "CPE Date": "2024-05-07T00:00:00",
    "Description of Activity": "In December 2021, the U.S. Surgeon General declared a youth mental health crisis. Suicide is the second leading cause of death among youth 10-24 years. To respond to this public health crisis, a large urban children\u2019s hospital system applied a public health framework to develop workgroups to address this complex issue, focused on research, training, workforce, family support, community engagement, and Zero Suicide. From November 2021 through March 2023, these committees assessed the problem; identified and developed resources and tools; and reflected upon lessons learned. These efforts are now integrated into the broader behavioral health response across the system.",
    "Link": "Full Schedule",
    "Hours": "1",
    "DoDI Criteria Topics": "Prevention of Harmful Behaviors"
  },
  {
    "COURSE CODE": "AAS24-016",
    "CPE Title": "Amplifying Youth Voice in Suicide Prevention: Empowering Youth Leaders for Transformative Change",
    "Part of Conference": "American Association of Suicidology 57th Annual Conference",
    "Sponsor": "American Association of Suicidology  ",
    "Virtual or Live": "In person",
    "Sponsor Type": "Professional Org",
    "CPE Date": "2024-05-07T00:00:00",
    "Description of Activity": "This engaging and dynamic presentation explores the vital role of youth voice in suicide prevention projects and programs. By incorporating their lived experience, we demonstrate how youth-led focus groups can enhance the content, increase engagement of services, and provide insightful recommendations for program improvement. Attendees will walk away from this session with tools to initiate and conduct youth focus groups that transform youth voice into strategies, policies, and practices that improve suicide prevention efforts and save lives.",
    "Link": "Full Schedule",
    "Hours": "1",
    "DoDI Criteria Topics": "Prevention of Harmful Behaviors"
  },
  {
    "COURSE CODE": "AAS24-017",
    "CPE Title": "Analyzing and Enhancing Imminent Risk Data within the 988 Suicide & Crisis Lifeline Network: A Comprehensive Exploration",
    "Part of Conference": "American Association of Suicidology 57th Annual Conference",
    "Sponsor": "American Association of Suicidology  ",
    "Virtual or Live": "In person",
    "Sponsor Type": "Professional Org",
    "CPE Date": "2024-05-07T00:00:00",
    "Description of Activity": "This symposium puts a spotlight on imminent risk data within the 988 Suicide & Crisis Lifeline network via the exploration of three critical topics. Topic 1 will provide a comprehensive review of 988 Lifeline imminent risk data, delving into various data sources and limitations. The presentation also will uncover the intricacies of interpreting imminent risk data and explore the origins of the 'less than 2%' figure for emergency service dispatch. Topic 2 will scrutinize the scientific literature, dissecting studies that focus on imminent risk calls within the Lifeline network. The presentation also will share insights into varying counselor approaches and key findings, while identifying future research needs. Topic 3 will shift focus to strategies for elevating the quality and reliability of imminent risk data within the 988 Lifeline. The presentation also will explore technological innovations at Vibrant Emotional Health that promise transformative improvements in data collection and analysis.",
    "Link": "Full Schedule",
    "Hours": "1",
    "DoDI Criteria Topics": "Prevention of Harmful Behaviors"
  },
  {
    "COURSE CODE": "AAS24-018",
    "CPE Title": "Answering the Call: Strategies to Reach First Responders",
    "Part of Conference": "American Association of Suicidology 57th Annual Conference",
    "Sponsor": "American Association of Suicidology  ",
    "Virtual or Live": "In person",
    "Sponsor Type": "Professional Org",
    "CPE Date": "2024-05-08T00:00:00",
    "Description of Activity": "The presentation covers the journey of the First Responder Suicide Prevention Task Force from its inception to its current status. The goals of the task force will be presented with the strategies that have been successful based on feedback the task force has received from first responders. Participants will leave with strategies they will be able to adapt and implement within their own communities.",
    "Link": "Full Schedule",
    "Hours": "1",
    "DoDI Criteria Topics": "Prevention of Harmful Behaviors"
  },
  {
    "COURSE CODE": "AAS24-019",
    "CPE Title": "ASPARC and Athens State University- Bringing Suicide Awareness, Education, Prevention, and Outreach to Rural Alabama",
    "Part of Conference": "American Association of Suicidology 57th Annual Conference",
    "Sponsor": "American Association of Suicidology  ",
    "Virtual or Live": "In person",
    "Sponsor Type": "Professional Org",
    "CPE Date": "2024-05-08T00:00:00",
    "Description of Activity": "Our mission at Athens State University is to reach out to our campus and beyond, in order to research, change and educate students, faculty, staff, and community about suicide. We seek to ensure that all of the people on our campus have the knowledge and the ability to assist someone who may be potentially suicidal. We wish to give a voice to those who feel too ashamed or powerless to seek help by letting them know someone is available to help. Education goes a long way to reduce the stigma of suicide.",
    "Link": "Full Schedule",
    "Hours": "1",
    "DoDI Criteria Topics": "Prevention of Harmful Behaviors"
  },
  {
    "COURSE CODE": "AAS24-020",
    "CPE Title": "Be Sensitive, Be Brave for Suicide Prevention Mental Health",
    "Part of Conference": "American Association of Suicidology 57th Annual Conference",
    "Sponsor": "American Association of Suicidology  ",
    "Virtual or Live": "In person",
    "Sponsor Type": "Professional Org",
    "CPE Date": "2024-05-05T00:00:00",
    "Description of Activity": "Joyce Chu, PhD Psychologist, Professor/Director Palo Alto University, Communtiy Connections; Christopher Weaver, PhD Pscyhologist, Professor Palo Alto University",
    "Link": "Full Schedule",
    "Hours": "4",
    "DoDI Criteria Topics": "Prevention of Harmful Behaviors"
  },
  {
    "COURSE CODE": "AAS24-021",
    "CPE Title": "CALM (Conversations on Access to Lethal Means) Conversations",
    "Part of Conference": "American Association of Suicidology 57th Annual Conference",
    "Sponsor": "American Association of Suicidology  ",
    "Virtual or Live": "In person",
    "Sponsor Type": "Professional Org",
    "CPE Date": "2024-05-08T00:00:00",
    "Description of Activity": "Access to lethal means, including medication and firearms, is a determining factor in the outcome for suicidal individuals. This course addresses relevant data on lethal means, and provides participants with crucial skills for how to ask about access to lethal methods, and engage with clients and their support system to reduce access until they are no longer at elevated risk.",
    "Link": "Full Schedule",
    "Hours": "1",
    "DoDI Criteria Topics": "Prevention of Harmful Behaviors"
  },
  {
    "COURSE CODE": "AAS24-022",
    "CPE Title": "Collaboration is a Superpower: How Incorporating Diverse Perspectives Can Strengthen Your Prevention Efforts",
    "Part of Conference": "American Association of Suicidology 57th Annual Conference",
    "Sponsor": "American Association of Suicidology  ",
    "Virtual or Live": "In person",
    "Sponsor Type": "Professional Org",
    "CPE Date": "2024-05-08T00:00:00",
    "Description of Activity": "Collaboration might not always be easy, but the benefits far outweigh the cost. This interactive session draws on the experiences of the Suicide Prevention Resource Center\u2019s Tribal Initiatives, Best Practices Registry, Belonging Initiatives, and Lived Experience Initiatives teams. The session showcases specific programs and examples of cross-team collaborative projects and explains how our collaborative efforts have supported and enhanced our suicide prevention work. The presenters will demonstrate how organizations can use collaboration to implement best practices, center lived experience, and include traditional Tribal practices and wisdom while centering equity and belonging in suicide prevention efforts.",
    "Link": "Full Schedule",
    "Hours": "1",
    "DoDI Criteria Topics": "Prevention of Harmful Behaviors"
  },
  {
    "COURSE CODE": "AAS24-023",
    "CPE Title": "Collaborative Solutions to Reduce Military Suicide",
    "Part of Conference": "American Association of Suicidology 57th Annual Conference",
    "Sponsor": "American Association of Suicidology  ",
    "Virtual or Live": "In person",
    "Sponsor Type": "Professional Org",
    "CPE Date": "2024-05-07T00:00:00",
    "Description of Activity": "The Veteran Community is at increased risk for Suicide and often are not meaningfully connected to services/treatment. Lessor known, however, is that Active Military Members are also at increased risk. EMPACT-Suicide Prevention Center has partnered with the USAF to provide Suicide and Mental Health Awareness training to active service members. This successful collaboration exemplifies the power of civilian-military cooperation to increase awareness and reduce suicide. Through this partnership, nearly 500 service-members have been trained in ASIST or MHFA-Veteran. The Armed Services are part of our community, and as such, community behavioral health should seek out opportunities to help support them.",
    "Link": "Full Schedule",
    "Hours": "1",
    "DoDI Criteria Topics": "Prevention of Harmful Behaviors"
  },
  {
    "COURSE CODE": "AAS24-024",
    "CPE Title": "Community-Engaged Partnerships to Enhance Suicide Prevention for Service Members, Veterans, and their Families",
    "Part of Conference": "American Association of Suicidology 57th Annual Conference",
    "Sponsor": "American Association of Suicidology  ",
    "Virtual or Live": "In person",
    "Sponsor Type": "Professional Org",
    "CPE Date": "2024-05-07T00:00:00",
    "Description of Activity": "The Texas Suicide Prevention Collaborative and the Texas Veterans Commission (TVC) have created a community-centered effort to address suicide prevention through upstream strategies. This initiative centers on the Military Veteran Peer Network (MVPN), its relationships with local suicide prevention coalitions, and the combined effort to build community capacity. This presentation highlights a core element of this partnership \u2013 early identification capacity to identify veterans at risk of suicide, creating connections, and assisting veterans into community care. 2022 outcomes suggest these efforts contribute to increased identification abilities, preparedness, and confidence relating to Veteran suicide risk.",
    "Link": "Full Schedule",
    "Hours": "1",
    "DoDI Criteria Topics": "Prevention of Harmful Behaviors"
  },
  {
    "COURSE CODE": "AAS24-025",
    "CPE Title": "Comprehensive Suicide Prevention Strategies for Colleges and Universities",
    "Part of Conference": "American Association of Suicidology 57th Annual Conference",
    "Sponsor": "American Association of Suicidology  ",
    "Virtual or Live": "In person",
    "Sponsor Type": "Professional Org",
    "CPE Date": "2024-05-09T00:00:00",
    "Description of Activity": "Given that national surveys demonstrate college students continue to report high levels of suicide ideation and suicide attempts there is clear need for colleges and universities to develop innovative approaches to suicide prevention. The purpose of this session is to review relevant suicide prevention data for college campuses and present innovative and economical intervention strategies that have been deployed across three campuses (one large state school, one mid-size private school, and one small private school). More specifically, this session will highlight interventions that promote a sense of belonging, enhance resiliency skills, and create greater access to mental health care services.",
    "Link": "Full Schedule",
    "Hours": "1",
    "DoDI Criteria Topics": "Prevention of Harmful Behaviors"
  },
  {
    "COURSE CODE": "AAS24-026",
    "CPE Title": "Connecticut National Guard: Current Approaches to Suicide Prevention/Intervention/Postvention",
    "Part of Conference": "American Association of Suicidology 57th Annual Conference",
    "Sponsor": "American Association of Suicidology  ",
    "Virtual or Live": "In person",
    "Sponsor Type": "Professional Org",
    "CPE Date": "2024-05-08T00:00:00",
    "Description of Activity": "The seminar will explore a range of subjects, covering the specific tools and tactics utilized by the CTNG BHT to address the distinct requirements of servicemen and women. Important areas of focus encompass an examination of their suicide prevention efforts, prompt intervention approaches, and vital post-intervention methods. The CTNG BHT will demonstrate their peer-to-peer support frameworks, which leverage the connectedness of fellow service members to provide valuable aid and direction.",
    "Link": "Full Schedule",
    "Hours": "1",
    "DoDI Criteria Topics": "Prevention of Harmful Behaviors"
  },
  {
    "COURSE CODE": "AAS24-027",
    "CPE Title": "Connecticut's Youth Crisis Continuum: Suicide Prevention, Intervention and Postvention",
    "Part of Conference": "American Association of Suicidology 57th Annual Conference",
    "Sponsor": "American Association of Suicidology  ",
    "Virtual or Live": "In person",
    "Sponsor Type": "Professional Org",
    "CPE Date": "2024-05-08T00:00:00",
    "Description of Activity": "Preventing youth suicide and addressing the mental health needs of children and youth requires a robust and effective crisis continuum. This session highlights Connecticut\u2019s work building an effective system of care focused on prevention and early intervention. A statewide mobile crisis model provides rapid, in-person responses, which helps keep children in their homes, schools, and communities and diverted from restrictive and more intensive care options. Additionally, urgent crisis centers provide children and families another alternative to hospital emergency departments. We will share insights on the collaborations that helped build the current system, challenges that were faced, and future directions.",
    "Link": "Full Schedule",
    "Hours": "1",
    "DoDI Criteria Topics": "Prevention of Harmful Behaviors"
  },
  {
    "COURSE CODE": "AAS24-028",
    "CPE Title": "Crisis Intervention: Public Service Collaboration in Supporting Service Members, Veterans and their Families",
    "Part of Conference": "American Association of Suicidology 57th Annual Conference",
    "Sponsor": "American Association of Suicidology  ",
    "Virtual or Live": "In person",
    "Sponsor Type": "Professional Org",
    "CPE Date": "2024-05-08T00:00:00",
    "Description of Activity": "Representatives from the Veterans Crisis Line (VCL) will provide an overview of what the VCL is, how they differ from the 988 Network, and how they are uniquely equipped to support Service Members, Veterans, and their Families (SMVF). The VCL was established in 2007 through the Joshua Omvig Veterans Suicide Prevention Act. Since then, the VCL has served over 7.2 million callers, 342,000 texters, and 885,000 chatters. Vibrant Emotional Health representatives will review the Veteran Amendment partnership between 988 centers, the VCL, and Vibrant. We will cover topics such as usage, relationship building with SMVF focused organizations, and lessons learned.",
    "Link": "Full Schedule",
    "Hours": "1",
    "DoDI Criteria Topics": "Prevention of Harmful Behaviors"
  },
  {
    "COURSE CODE": "FRSU24-001",
    "CPE Title": "CPSY 901: Theories of Psychotherapy",
    "Part of Conference": "nan",
    "Sponsor": "Framingham State University Graduate Studies ",
    "Virtual or Live": "In-person",
    "Sponsor Type": "Accredited Institution",
    "CPE Date": "2024-12-18T00:00:00",
    "Description of Activity": "An examination of the theoretical, empirical bases, and application of the various counseling models. Students explore the nature of the client-therapist relationship in the context of different approaches and techniques of psychotherapy and counseling (e.g., psychoanalytic, behavior modification, client-centered, rational-emotive, and family systems). Open to non-matriculated students. Prerequisites: PSYC 215 Psychology of Personality or PSYC 322 Abnormal Psychology or the equivalent.",
    "Link": "https://www.framingham.edu/academics/graduate/counseling-psychology-ma",
    "Hours": "60",
    "DoDI Criteria Topics": "Prevention of Harmful Behaviors; Children/Youth/Families"
  },
  {
    "COURSE CODE": "FRSU24-002",
    "CPE Title": "CPSY 921: Professional Issues in Counseling and Mental Health",
    "Part of Conference": "nan",
    "Sponsor": "Framingham State University Graduate Studies ",
    "Virtual or Live": "In-person",
    "Sponsor Type": "Accredited Institution",
    "CPE Date": "2024-12-18T00:00:00",
    "Description of Activity": "A consideration of the ethical and legal issues relevant to the counseling and mental health professions. This course reviews the ethical principles of the American Psychological Association and the American Counseling Association. The history of the counseling profession is covered with emphasis on the emerging role of the mental health counselor. Topics explored include certification, licensure, federal and state regulations (e.g., confidentiality, duty to warn), and professional identity.",
    "Link": "https://www.framingham.edu/academics/graduate/counseling-psychology-ma",
    "Hours": "60",
    "DoDI Criteria Topics": "Leadership Development"
  },
  {
    "COURSE CODE": "IBP24-001",
    "CPE Title": "Reasoning with Unreasonable People: Focus on Disorders of Emotion Regulation",
    "Part of Conference": "nan",
    "Sponsor": "Institute for Brain Potential",
    "Virtual or Live": "In-person",
    "Sponsor Type": "Professional Org",
    "CPE Date": "2024-10-03T00:00:00",
    "Description of Activity": "In this program, health professionals will learn how people reason with selected disorders of mood, anxiety, OCD, anger, and personality. Practical strategies will be presented to facilitate meaningful change in patients and health professionals working in medical, dental, and behavioral health settings. Participants completing this program should be able to: 1. List several paths to achieving effective emotional communication. 2. Outline an effective strategy to reason with a person who has a disorder of mood, anxiety, OCD, anger, or personality. 3. Describe a strategy for reasoning or having a difficult conversation with a person who is experiencing pain, illness or vulnerability. 4. Describe a calming strategy including the practice of mindfulness for health professionals who are experiencing strong emotions.",
    "Link": "https://www.ibpceu.com/IBP/seminars",
    "Hours": "6",
    "DoDI Criteria Topics": "Prevention of Harmful Behaviors; Program Eval-Research-Data"
  },
  {
    "COURSE CODE": "UICE25-001",
    "CPE Title": "Counseling on Access to Lethal Means (CALM)",
    "Part of Conference": "nan",
    "Sponsor": "University of Iowa Center of Excellence for Behavioral Health",
    "Virtual or Live": "Virtual",
    "Sponsor Type": "Accredited Institution",
    "CPE Date": "2025-02-12T00:00:00",
    "Description of Activity": "This is a video about Counseling on Access to Lethal Means (CALM) recorded by the University of Iowa Center for Excellence in Behavioral Health 2/12/25",
    "Link": "https://www.iowacebh.org/2025-trainings-archive/",
    "Hours": "1",
    "DoDI Criteria Topics": "Prevention of Harmful Behaviors; Program Eval-Research-Data"
  },
  {
    "COURSE CODE": "LSUS24-001",
    "CPE Title": "Bullying Prevention And Suicide Prevention Conference",
    "Part of Conference": "Louisiana State University in Shreveport Bullying Prevention And Suicide Prevention Conference",
    "Sponsor": "LSU Shreveport",
    "Virtual or Live": "In-Person",
    "Sponsor Type": "Accredited Institution",
    "CPE Date": "2024-10-18T00:00:00",
    "Description of Activity": "LSUS Conference on Bullying and Suicide Prevention, multiple presentations provided-- NASW, Bossier Parrish Schools & LSUS Dept of Phycology approved for 6 credit hrs. ",
    "Link": "https://naswla.org/Shared_Content/Events/Event_Display.aspx?EventKey=253513_069",
    "Hours": "6",
    "DoDI Criteria Topics": "Children/Youth/Families; Prevention of harmful behaviors"
  },
  {
    "COURSE CODE": "FARB24-001",
    "CPE Title": "Secure Firearm Storage and Suicide Prevention",
    "Part of Conference": "The David Farber ASPIRE Center Suicide Prevention Symposium",
    "Sponsor": "Jefferson Health, Thomas Jefferson University and co-sponsored by Drexel University, Philadelphia, PA",
    "Virtual or Live": "In-Person",
    "Sponsor Type": "Accredited Institution",
    "CPE Date": "2024-04-10T00:00:00",
    "Description of Activity": "This 1-day in-person event is the first Suicide Prevention Symposium organized by the David Farber ASPIRE (Advancement of Suicide Prevention, Intervention, Research, and Education) Center at Thomas Jefferson University, dedicated to advancing the prevention of substance use and misuse. Requesting 1.5 hours of CPE for Secure Firearm Storage and Suicide Prevention.",
    "Link": "https://www.jeffersonhealth.org/your-health/classes-and-events/suicide-prevention-symposium",
    "Hours": "1.5",
    "DoDI Criteria Topics": "Prevention of Harmful Behaviors; Program Eval-Research-Data "
  },
  {
    "COURSE CODE": "AAS24-029",
    "CPE Title": "Considerations for \"The Deadly Gap\" - The Elevated Suicide Risk for Military in the First Year After Service Separation",
    "Part of Conference": "American Association of Suicidology 57th Annual Conference",
    "Sponsor": "American Association of Suicidology  ",
    "Virtual or Live": "In person",
    "Sponsor Type": "Professional Org",
    "CPE Date": "2024-05-07T00:00:00",
    "Description of Activity": "In the first year after leaving military service, the rate of veteran suicide is 2.5x higher compared to the active-duty population. During this time, veterans are experiencing change in all major areas of life: family, job, community, friendships, and life purpose. We will discuss why these changes can be so overwhelming from a neuroscience perspective (e.g. resistance to change), the impact of substance use and access to lethal means, and discuss the various programs and places in the community that can provide support.",
    "Link": "Full Schedule",
    "Hours": "1",
    "DoDI Criteria Topics": "Prevention of Harmful Behaviors"
  },
  {
    "COURSE CODE": "AAS24-030",
    "CPE Title": "The CDC Comprehensive Suicide Prevention Program: Using Data to Drive Action",
    "Part of Conference": "American Association of Suicidology 57th Annual Conference",
    "Sponsor": "American Association of Suicidology  ",
    "Virtual or Live": "In person",
    "Sponsor Type": "Professional Org",
    "CPE Date": "2024-05-07T00:00:00",
    "Description of Activity": "Provisional 2022 data show suicide deaths continue to rise (49,498 vs 48,183 in 2021; a 2.7% increase). This session will highlight data on suicide and an overview on CDC\u2019s effort to implement a comprehensive suicide prevention program (CSP) which includes funding to the Colorado Department of Public Health and Environment. Despite a 27% statewide increase in suicide rates from 2019-2021, the Colorado CSP program observed only a 1.4% increase in suicide rates among the 6-county CSP coverage area and the lowest number of veteran suicides in 2022 (n=198). These examples can inform public health action to prevent suicide.",
    "Link": "Full Schedule",
    "Hours": "1",
    "DoDI Criteria Topics": "Prevention of Harmful Behaviors"
  },
  {
    "COURSE CODE": "AAS24-031",
    "CPE Title": "LivingWorks safeTALK: Suicide Alertness and Safety Connection Skills",
    "Part of Conference": "American Association of Suicidology 57th Annual Conference",
    "Sponsor": "American Association of Suicidology  ",
    "Virtual or Live": "In person",
    "Sponsor Type": "Professional Org",
    "CPE Date": "2024-05-05T00:00:00",
    "Description of Activity": "Richard Egan, Suicide Prevention Training and Outreach Facilitator - State of Nevada, Office of Suicide Prevention  LivingWorks safeTALK is a four-hour training that equips people to be more alert to someone thinking of suicide and better able to connect them with further help. Using a simple yet effective model, LivingWorks safeTALK empowers everyone to make a difference. With over 120,000 people attending each year, it\u2019s the world\u2019s fastest-growing suicide prevention skills training course.",
    "Link": "Full Schedule",
    "Hours": "4",
    "DoDI Criteria Topics": "Prevention of Harmful Behaviors"
  },
  {
    "COURSE CODE": "AAS24-032",
    "CPE Title": "MAD HOPE: A Youth Suicide Prevention Education Program",
    "Part of Conference": "American Association of Suicidology 57th Annual Conference",
    "Sponsor": "American Association of Suicidology  ",
    "Virtual or Live": "In person",
    "Sponsor Type": "Professional Org",
    "CPE Date": "2024-05-08T00:00:00",
    "Description of Activity": "In this conference presentation, attendees will learn about the MAD HOPE Youth Suicide Prevention and Mental Well-Being program (located in Bellingham, Washington). This session will cover the training curriculum, suicidology and prevention best practices that inform its creation, our Train the Trainer and volunteer support models, and creating and maintaining our community partnerships with area schools. Attendees will also be presented with our data, including feedback from student and teacher evaluations. This presentation will give inspiration and practical information, ideas, and strategies to create similar youth suicide prevention training programs in their communities.",
    "Link": "Full Schedule",
    "Hours": "1",
    "DoDI Criteria Topics": "Prevention of Harmful Behaviors"
  },
  {
    "COURSE CODE": "AAS24-033",
    "CPE Title": "Making Virtual Suicide Prevention a Reality: Using Virtual Behavioral Health to Expand Access and Fill the Gaps in Care",
    "Part of Conference": "American Association of Suicidology 57th Annual Conference",
    "Sponsor": "American Association of Suicidology  ",
    "Virtual or Live": "In person",
    "Sponsor Type": "Professional Org",
    "CPE Date": "2024-05-09T00:00:00",
    "Description of Activity": "Virtual behavioral health care models can expand access to services in communities that do not have enough resources to meet the need. Learn how one multi-state health system\u2019s centralized, virtual behavioral health team partnered with their Zero Suicide implementation committee to redesign suicide care pathways in emergency department and primary care settings to fill the gaps in care and improve clinical quality.",
    "Link": "Full Schedule",
    "Hours": "1",
    "DoDI Criteria Topics": "Prevention of Harmful Behaviors"
  },
  {
    "COURSE CODE": "AAS24-034",
    "CPE Title": "Male Suicide is Killing Us",
    "Part of Conference": "American Association of Suicidology 57th Annual Conference",
    "Sponsor": "American Association of Suicidology  ",
    "Virtual or Live": "In person",
    "Sponsor Type": "Professional Org",
    "CPE Date": "2024-05-08T00:00:00",
    "Description of Activity": "Male suicide is literally killing us. Eighty percent of suicide decedents in the United of America are men but you would never know this from our suicide prevention messaging or high priority populations. How did the field of suicide prevention miss the largest population of suicide victims in our suicide prevention efforts? What are the evolutionary and cultural factors driving male suicide? This presentation will address these vital questions and also explore potential solutions to our male suicide problem. We are losing uncles, nephews, brothers, fathers, and sons to suicide at an alarming rate. It is time to fix that.",
    "Link": "Full Schedule",
    "Hours": "1",
    "DoDI Criteria Topics": "Prevention of Harmful Behaviors"
  },
  {
    "COURSE CODE": "AAS24-035",
    "CPE Title": "Mental Health Providers as Grief Survivors: Findings from a Two Year Drop in Loss Group",
    "Part of Conference": "American Association of Suicidology 57th Annual Conference",
    "Sponsor": "American Association of Suicidology  ",
    "Virtual or Live": "In person",
    "Sponsor Type": "Professional Org",
    "CPE Date": "2024-05-07T00:00:00",
    "Description of Activity": "The focus of the workshop is to share the findings from a survey of mental health providers who attended a drop in bereavement group for providers, and will discuss the interventions that were used. Recommendations will be made to clinical supervisors and organizations that experience client loss on how to reduce stigma. Experiential learning will be used to practice grief interventions.",
    "Link": "Full Schedule",
    "Hours": "1",
    "DoDI Criteria Topics": "Prevention of Harmful Behaviors"
  },
  {
    "COURSE CODE": "AAS24-036",
    "CPE Title": "Mental Wellness Begins at Home",
    "Part of Conference": "American Association of Suicidology 57th Annual Conference",
    "Sponsor": "American Association of Suicidology  ",
    "Virtual or Live": "In person",
    "Sponsor Type": "Professional Org",
    "CPE Date": "2024-05-09T00:00:00",
    "Description of Activity": "Officers cannot just \u201cturn it off\u201d when they arrive home to their family. What happens on the job can spill over at home and negatively impact home life. Home life can spill over and negatively impact an officer at work, becoming a safety issue at work and on the officer\u2019s mental health. In this session, learn the five elements that every law enforcement couple needs to know to counter the impact of the spillover that impacts a couple\u2019s communication, connection, and intimacy, essential elements of a relationship based upon research.",
    "Link": "Full Schedule",
    "Hours": "1",
    "DoDI Criteria Topics": "Prevention of Harmful Behaviors"
  },
  {
    "COURSE CODE": "AAS24-037",
    "CPE Title": "Navigating Change: A Dialogic Approach to Enhancing Crisis Line Services in British Columbia, Canada",
    "Part of Conference": "American Association of Suicidology 57th Annual Conference",
    "Sponsor": "American Association of Suicidology  ",
    "Virtual or Live": "In person",
    "Sponsor Type": "Professional Org",
    "CPE Date": "2024-05-08T00:00:00",
    "Description of Activity": "\u00a0In an effort to enhance crisis line services in British Columbia, in 2021 BC Mental Health and Substance Use services launched a provincial Crisis Line Enhancement Project (CLEP). Key goals of this initiative were to: (1) increase capacity to meet demand; (2) standardize the quality and consistency of crisis line services, and; (3) strengthen provincial accountability and governance. This session describes the application of the Dialogic Organizational Change model, which leverages the diverse perspectives of service providers, service users and other key partners to enable the delivery of high-quality, accessible, appropriate, and consistent crisis line services across the province.",
    "Link": "Full Schedule",
    "Hours": "1",
    "DoDI Criteria Topics": "Prevention of Harmful Behaviors"
  },
  {
    "COURSE CODE": "AAS24-038",
    "CPE Title": "Ohio's Current Suicide Fatality Review Infrastructure & Future Outlook",
    "Part of Conference": "American Association of Suicidology 57th Annual Conference",
    "Sponsor": "American Association of Suicidology  ",
    "Virtual or Live": "In person",
    "Sponsor Type": "Professional Org",
    "CPE Date": "2024-05-08T00:00:00",
    "Description of Activity": "Ohio is currently implementing suicide fatality review boards and psychological autopsies across the state. However, these initiatives are fairly new, and a state team is taking a unique approach to support and develop local suicide fatality review boards while integrating newly-trained psychological autopsy investigators to create a more robust death review system. Participants will receive an overview of suicide fatality review, psychological autopsy, and how these two initiatives differ (and are related). This can create an innovative system that can contribute to both streamlined suicide death data collection, but can also inform future suicide prevention efforts.",
    "Link": "Full Schedule",
    "Hours": "1",
    "DoDI Criteria Topics": "Prevention of Harmful Behaviors"
  },
  {
    "COURSE CODE": "AAS24-039",
    "CPE Title": "Postvention Intelligence Framework Assessment (PIFA): Evaluating Post-Suicide Mental Health for Self, Others, and Organizations",
    "Part of Conference": "American Association of Suicidology 57th Annual Conference",
    "Sponsor": "American Association of Suicidology  ",
    "Virtual or Live": "In person",
    "Sponsor Type": "Professional Org",
    "CPE Date": "2024-05-08T00:00:00",
    "Description of Activity": "Given the continued increase of suicide, development of the Postvention Intelligence Framework and Assessment (PIFA) provides a healthy way of educating professionals to talk about postvention and reduce the stigma of asking for help. Participants will discuss the Postvention Intelligence Framework and Assessment (PIFA) with the framework\u2019s creators and each other to understand their own PI score. The PIFA is used as a framework to increase awareness, foster stronger connections, and open pathways that influence positive outcomes at the self, team, and organizational levels. Freedom from stigma and freedom from psychological pain post suicide are important freedoms for all people.",
    "Link": "Full Schedule",
    "Hours": "1",
    "DoDI Criteria Topics": "Prevention of Harmful Behaviors"
  },
  {
    "COURSE CODE": "AAS24-040",
    "CPE Title": "Practical Strategies to Develop and Maintain Partnership-Focused Campus Suicide Prevention Programs",
    "Part of Conference": "American Association of Suicidology 57th Annual Conference",
    "Sponsor": "American Association of Suicidology  ",
    "Virtual or Live": "In person",
    "Sponsor Type": "Professional Org",
    "CPE Date": "2024-05-09T00:00:00",
    "Description of Activity": "Many colleges have suicide prevention programs. Often these are initially grant funded, are situated with existing offices, and have limited programming. By creating a stand-alone program, supported and funded by multiple partners and with more than 250 faculty, staff, and student volunteers, these presenters have sustained a comprehensive campus suicide prevention program for 18 years. Participants with learn practical strategies for developing a partnership-based comprehensive program on their campus, with emphasis on sustainability.",
    "Link": "Full Schedule",
    "Hours": "1",
    "DoDI Criteria Topics": "Prevention of Harmful Behaviors"
  },
  {
    "COURSE CODE": "AAS24-041",
    "CPE Title": "Presenting a Novel Approach to Suicide Prevention Pathways",
    "Part of Conference": "American Association of Suicidology 57th Annual Conference",
    "Sponsor": "American Association of Suicidology  ",
    "Virtual or Live": "In person",
    "Sponsor Type": "Professional Org",
    "CPE Date": "2024-05-08T00:00:00",
    "Description of Activity": "\u00a0Suicide pathway (decision tree) strategies focus primarily on screening for suicide ideation for client identification. These have significant limitations because research suggests most clients who die by suicide in behavioral healthcare do not overtly express suicide ideation when inquired. Centerstone's Zero Suicide initiative has been focusing on widening the net of screening to identify covert ideation and risk factors for future ideation in addition to related risk areas (i.e., violence potential) to capture more clients in interventions to prevent suicide. We will discuss these development initiatives and include pilot test results and new pathway descriptions and interventions.",
    "Link": "Full Schedule",
    "Hours": "1",
    "DoDI Criteria Topics": "Prevention of Harmful Behaviors"
  },
  {
    "COURSE CODE": "AAS24-042",
    "CPE Title": "Proactive Community-Based Strategies for Suicide Prevention Among Service Members and Veterans: The Importance of Military Service History Screening",
    "Part of Conference": "American Association of Suicidology 57th Annual Conference",
    "Sponsor": "American Association of Suicidology  ",
    "Virtual or Live": "In person",
    "Sponsor Type": "Professional Org",
    "CPE Date": "2024-05-08T00:00:00",
    "Description of Activity": "\u00a0Explore the vital role of military service screening in preventing veteran suicide in this insightful presentation. Uncover the alarming disparity in veteran suicide rates and the systemic gaps in healthcare provider readiness. Learn from the success of Virginia's VISR program and Policy Research Associates, Inc.'s strategic implementation support, gaining a deeper understanding of effective interventions. This session delivers a comprehensive overview of the screening challenges and solutions in veteran healthcare, highlighting the necessity and impact of integrating military service screening into healthcare practices.",
    "Link": "Full Schedule",
    "Hours": "1",
    "DoDI Criteria Topics": "Prevention of Harmful Behaviors"
  },
  {
    "COURSE CODE": "AAS24-043",
    "CPE Title": "Promoting Community Conversations Around Research to End Suicide",
    "Part of Conference": "American Association of Suicidology 57th Annual Conference",
    "Sponsor": "American Association of Suicidology  ",
    "Virtual or Live": "In person",
    "Sponsor Type": "Professional Org",
    "CPE Date": "2024-05-08T00:00:00",
    "Description of Activity": "Promoting Community Conversations Around Research to End Suicide (PC CARES) is a community-learning model that gives scientific information to community members that offer tools and ideas about how best to prevent suicide and promote wellness. We do this with what we call learning circles. People who attend PC CARES learn, discuss, and make plans to prevent suicide and promote wellness in their community. By bringing bite sized pieces of research directly to communities and giving them an opportunity to decide how to use the research information, PCCARES creates sustainable, positive change.",
    "Link": "Full Schedule",
    "Hours": "1",
    "DoDI Criteria Topics": "Prevention of Harmful Behaviors"
  },
  {
    "COURSE CODE": "AAS24-044",
    "CPE Title": "QPR Gatekeeper Instructor Certification Course",
    "Part of Conference": "American Association of Suicidology 57th Annual Conference",
    "Sponsor": "American Association of Suicidology  ",
    "Virtual or Live": "In person",
    "Sponsor Type": "Professional Org",
    "CPE Date": "2024-05-06T00:00:00",
    "Description of Activity": "Shayna Klassen, BA - National Training Director, QPR Institute Becoming a certified trainer of QPR\u2019s industry-leading approach to suicide prevention is an excellent way for individuals and organizations to help empower their communities to effectively intervene on behalf of suicidal and in-crisis people. Gatekeeper Training Certification 3-year Certification",
    "Link": "Full Schedule",
    "Hours": "8",
    "DoDI Criteria Topics": "Prevention of Harmful Behaviors"
  },
  {
    "COURSE CODE": "AAS24-045",
    "CPE Title": "QPR Gatekeeper Training",
    "Part of Conference": "American Association of Suicidology 57th Annual Conference",
    "Sponsor": "American Association of Suicidology  ",
    "Virtual or Live": "In person",
    "Sponsor Type": "Professional Org",
    "CPE Date": "2024-05-06T00:00:00",
    "Description of Activity": "Samantha Nadler, MSSW - American Association of Suicidology Our Gatekeeper course is taught in a clear, concise format using the latest in educational technology and practices. The course takes approximately one hour to complete. Training participants to teach QPR Gatekeeper Training for Suicide Prevention, Understanding the nature and range of suicidal communications, Knowing the groups at greatest risk of suicide and why QPR can work for them Suicide and suicide prevention in history Gatekeeper training; how, why and the research; New and promising approaches to suicide prevention; How QPR fits into national efforts; KEY COMPONENTS COVERED IN TRAINING: How to Question, Persuade and Refer someone who may be suicidal; How to get help for yourself or learn more about preventing suicide; The common causes of suicidal behavior; The warning signs of suicide; How to get help for someone in crisis",
    "Link": "Full Schedule",
    "Hours": "2.5",
    "DoDI Criteria Topics": "Prevention of Harmful Behaviors"
  },
  {
    "COURSE CODE": "AAS24-046",
    "CPE Title": "Rapidly Implementing Evidence-Based Suicide Prevention Interventions in a Pediatric Bridge Mental Health Care Clinic",
    "Part of Conference": "American Association of Suicidology 57th Annual Conference",
    "Sponsor": "American Association of Suicidology  ",
    "Virtual or Live": "In person",
    "Sponsor Type": "Professional Org",
    "CPE Date": "2024-05-09T00:00:00",
    "Description of Activity": "Following the Joint Commission\u2019s 2019 mandate to expand suicide screening, rapidly developing suicide prevention interventions for newly identified high acuity patients became a priority for pediatric hospitals. This session will focus upon learning from one Midwestern hospital\u2019s implementation of two evidence-based suicide prevention interventions within a nine month period in a pediatric bridge mental health clinic. Discussion will focus upon projected days of life save and additional revenue generated as a result of this combined initiative. Lessons learned and sample clinical workflows will be discussed to aid other systems in launching their own initiatives.",
    "Link": "Full Schedule",
    "Hours": "1",
    "DoDI Criteria Topics": "Prevention of Harmful Behaviors"
  },
  {
    "COURSE CODE": "AAS24-047",
    "CPE Title": "Readiness to Stand United Against Youth Suicide: A New Jersey Public Health Statewide Initiative",
    "Part of Conference": "American Association of Suicidology 57th Annual Conference",
    "Sponsor": "American Association of Suicidology  ",
    "Virtual or Live": "In person",
    "Sponsor Type": "Professional Org",
    "CPE Date": "2024-05-08T00:00:00",
    "Description of Activity": "New Jersey\u2019s Garrett Lee Smith Grant (GLS): Readiness to Stand United Against Youth Suicide is New Jersey's Public Health Statewide Initiative and collaboration of State Departments, community-based and professional organizations, and persons with lived experience across multiple sectors. The key to New Jersey\u2019s early and continuous success with GLS has been achieved through partnership, collaboration, and continuous quality improvement. This presentation will help provide an informational foundation to guide other states and organizations seeking to provide effective and sustainable suicide prevention and intervention services to youth based in collaborations and partnerships.",
    "Link": "Full Schedule",
    "Hours": "1",
    "DoDI Criteria Topics": "Prevention of Harmful Behaviors"
  },
  {
    "COURSE CODE": "AAS24-048",
    "CPE Title": "Recent Developments in Research on the Interpersonal Theory of Suicide",
    "Part of Conference": "American Association of Suicidology 57th Annual Conference",
    "Sponsor": "American Association of Suicidology  ",
    "Virtual or Live": "In person",
    "Sponsor Type": "Professional Org",
    "CPE Date": "2024-05-07T00:00:00",
    "Description of Activity": "This symposium presents recent advances in research on the Interpersonal Theory of Suicide (ITS). Three presenters will provide an overview of their recent research and facilitate discussion of research findings with respect to advancing theory, research, and clinical services for individuals experiencing suicide-related thoughts and behaviors. Presentations include an examination of role of hopelessness in the ITS and predictive validity of the ITS in a sample of military personnel, an examination of the ITS in the context of social determinants of health, and an examination of the role of contribution to others as contributing factor in perceived burdensomeness. This symposium aims to provide attendees with cutting edge findings that can inform both clinical and research efforts",
    "Link": "Full Schedule",
    "Hours": "1",
    "DoDI Criteria Topics": "Prevention of Harmful Behaviors"
  },
  {
    "COURSE CODE": "AAS24-049",
    "CPE Title": "Reducing Jail Suicides: 8 Key Issues We Don't Talk About, But Should",
    "Part of Conference": "American Association of Suicidology 57th Annual Conference",
    "Sponsor": "American Association of Suicidology  ",
    "Virtual or Live": "In person",
    "Sponsor Type": "Professional Org",
    "CPE Date": "2024-05-09T00:00:00",
    "Description of Activity": "Suicide is the leading cause of death in jails. This high-energy and interactive session focuses on (8) key issues related to correctional suicide that must be addressed to truly reduce the number of incarcerated individuals who kill themselves. Attendees will learn about complexities and challenges specific to suicide prevention in jail settings, as well as how minor modifications to a jail\u2019s suicide prevention program can potentially reduce residents\u2019 unbearable distress and desire to escape it. Practical presentation by a jail suicide expert with case examples, audience participation, and lessons learned from individuals with lived experience, as well as suicide-related research.",
    "Link": "Full Schedule",
    "Hours": "1",
    "DoDI Criteria Topics": "Prevention of Harmful Behaviors"
  },
  {
    "COURSE CODE": "AAS24-050",
    "CPE Title": "Screening for Suicide Risk During Teleheath Visits",
    "Part of Conference": "American Association of Suicidology 57th Annual Conference",
    "Sponsor": "American Association of Suicidology  ",
    "Virtual or Live": "In person",
    "Sponsor Type": "Professional Org",
    "CPE Date": "2024-05-07T00:00:00",
    "Description of Activity": "Continuing to identify suicide risk during telehealth visits is critical, as the demand for telehealth services persists. Screening for suicide risk during healthcare visits continues to grow as a standard care practice. While there are a variety of available and validated screening tools available for use, clinicians may be less comfortable screening for suicide risk during telehealth visits compared to in-person visits. This session focuses on thoughtful approaches to screening for suicide risk in telehealth, managing suicide risk collaboratively, and proactively involving family and supportive others in care and telehealth sessions. Resources, tools, and best practice guidance will be highlighted.",
    "Link": "Full Schedule",
    "Hours": "1",
    "DoDI Criteria Topics": "Prevention of Harmful Behaviors"
  },
  {
    "COURSE CODE": "AAS24-051",
    "CPE Title": "Shifting Perspectives: Caring Contacts Implementation at a Health Plan",
    "Part of Conference": "American Association of Suicidology 57th Annual Conference",
    "Sponsor": "American Association of Suicidology  ",
    "Virtual or Live": "In person",
    "Sponsor Type": "Professional Org",
    "CPE Date": "2024-05-08T00:00:00",
    "Description of Activity": "Health insurance\u2019s evolution in mental health care, emphasizing suicide prevention, has shifted towards proactive strategies. This presentation explores a Southern US health plan\u2019s transformative journey implementing Caring Contacts, an evidence-based approach. Addressing the 11th leading cause of US adult deaths, the program showcases promising outcomes, emphasizing early intervention, tailored support, and a proactive approach to mental health care.",
    "Link": "Full Schedule",
    "Hours": "1",
    "DoDI Criteria Topics": "Prevention of Harmful Behaviors"
  },
  {
    "COURSE CODE": "AAS24-052",
    "CPE Title": "Student Advocacy Specialist- Who, What and How We Support our Suicidal and Homicidal Students in Crisis Through Personal Connections and System Supports",
    "Part of Conference": "American Association of Suicidology 57th Annual Conference",
    "Sponsor": "American Association of Suicidology  ",
    "Virtual or Live": "In person",
    "Sponsor Type": "Professional Org",
    "CPE Date": "2024-05-08T00:00:00",
    "Description of Activity": "The Student Advocacy Specialist (SAS) role in the Forsyth County School system aims to provide support for students through mentorship, psychoeducation, and safety planning. The SAS role supports all students but more specifically, they support students with current suicidal ideation, homicidal ideation, and self-harming behaviors as well as students with histories of these thoughts and behaviors.",
    "Link": "Full Schedule",
    "Hours": "1",
    "DoDI Criteria Topics": "Prevention of Harmful Behaviors"
  },
  {
    "COURSE CODE": "AAS24-053",
    "CPE Title": "Suicide Prevention in Rural Farming Communities",
    "Part of Conference": "American Association of Suicidology 57th Annual Conference",
    "Sponsor": "American Association of Suicidology  ",
    "Virtual or Live": "In person",
    "Sponsor Type": "Professional Org",
    "CPE Date": "2024-05-09T00:00:00",
    "Description of Activity": "\u00a0Suicide Prevention and 988 in Georgia among rural populations and farmers has become extremely important since COVID 19. Learn about the data and research related to this population, the current initiatives for this demographic in Georgia, and how to create and distrbute effective messaging among this demographic.",
    "Link": "Full Schedule",
    "Hours": "1",
    "DoDI Criteria Topics": "Prevention of Harmful Behaviors"
  }
];